env_settings:
  # env_path: ../../Builds/Current_Build_NoGraphics
  num_envs: 8

engine_settings:
  no_graphics: true

behaviors:
  Car:
    trainer_type: ppo

    hyperparameters:
      batch_size: 3000 # Should be larger for continuous actions
      buffer_size: 30000 # larger buff size means more stables training updates
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear

    network_settings:
      vis_encode_type: simple
      normalize: true # Normalization can be helpful in cases with complex continuous control problems so it was enabled
      hidden_units: 128
      num_layers: 2

    reward_signals:

      extrinsic:
        gamma: 0.99
        strength: 1.0

      gail:
        gamma: 0.99
        strength: 0.01 # Set lower since demos are suboptimal
        demo_path: /Users/karlestes/Documents/Grad School/CSC 525 - Principles of Machine Learning/Portfolio Project/AI_Vehicle/Assets/ML-Agents/Demonstrations/
        learning_rate: 1.0e-4
        use_actions: false
        use_vail: true # Enable if imitation learning has some trouble

        network_settings:
          hidden_units: 64
          num_layers: 2

    max_steps: 20000000
    time_horizon: 1500
    summary_freq: 15000
    checkpoint_interval: 500000
    keep_checkpoints: 15
    threaded: false

    